fix: exit code

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,8 +28,18 @@ jobs:
             - name: Generate Test Report
               id: generate_report
               run: |
-                  pytest --junitxml=report.xml  # Example for pytest JUnit XML report
-                  echo "::set-output name=report::$(cat report.xml)"
+                  pytest > output.txt
+                  echo "::set-output name=report::$(cat output.txt)"
+
+            - name: Check Exit Code and Set Output
+              if: always()
+              run: |
+                  exit_code=$?
+                  if [ $exit_code -eq 5 ] || [ $exit_code -eq 0 ]; then
+                    echo "Exit code indicates success. Continuing..."
+                  else
+                    echo "::error::Unexpected exit code: $exit_code. Failing the action."
+                    exit $exit_code
 
             - name: Send Report via Webhook
               uses: rjstone/discord-webhook-notify@v1.1.1
@@ -39,6 +49,6 @@ jobs:
                   webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
                   text: "Test Results for branch ${{ github.ref_name }} on ${{ github.repository }}"
                   description: |
-                      ```
+                      ```console
                           ${{ steps.generate_report.outputs.report }}
                       ```
